services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  test:
    build: .
    volumes:
      - .:/app
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_USER=test_user
      - MONGODB_PASSWORD=test_password
      - ENVIRONMENT=test
      - PYTHONPATH=/app
    command: pytest tests/ -v --color=yes
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test_user
      - MONGO_INITDB_ROOT_PASSWORD=test_password
    ports:
      - "27017:27017"
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 3